# Generated by Django 3.1.6 on 2021-02-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
